name: CI

#Déf de la stratégie
on: 
  pull_request:
    branches:
     - dev
  push:
    branches:
      - prod
    branches-ignore:
      - staging


jobs: 
  build_docker:
    runs-on: ubuntu-latest
    steps:
      - name: install checkout
        uses: docker/checkout@v7
      - name: check version docker
        run:
          docker --version
          docker compose version
      - name: docker up
        run: docker compose up